version: '1.1.0-beta{build}'
configuration:
#  - Debug
  - Release

build_script:
  - dotnet build
  - dotnet msbuild /p:Configuration=Release

test_script:
  - dotnet test StandartClassLibrary --framework netcoreapp2.0
  - dotnet test StandartClassLibrary --framework net452
