version: '1.1.0-beta{build}'
configuration:
#  - Debug
  - Release

build_script:
  - dotnet build
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./UnitTestProject1/bin/Release/UnitTestProject1.dll

test_script:
  - dotnet test StandartClassLibrary --framework netcoreapp2.0
  - dotnet test StandartClassLibrary --framework net452
