version: '1.1.0-beta{build}'
configuration:
#  - Debug
  - Release

install:
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory ./testrunner

build_script:
  - tree
  - ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./StandartClassLibrary/bin/Release/net452/StandartClassLibrary.dll
  - dotnet build

test_script:
  - dotnet test StandartClassLibrary --framework netcoreapp2.0
  - dotnet test StandartClassLibrary --framework net452
