version: '1.1.0-beta{build}'
configuration:
  - Debug
  - Release

build_script:
  - dotnet build
  - dotnet msbuild #/p:Configuration=Release
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner

test_script:
  - #--framework netcoreapp2.0 and net452
  - dotnet test SomeTests
  # direct tests
  - .\testrunner\xunit.runner.console.2.3.1\tools\net452\xunit.console.exe .\SomeTests\bin\%CONFIGURATION%\net452\SomeTests.dll
