language: csharp
solution: SimpleApp.sln
dotnet: 2.0.0
install:
  - nuget restore SimpleApp.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
script:
  #- xbuild /p:Configuration=Release SimpleApp.sln
  #- mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./UnitTestProject1/bin/Release/UnitTestProject1.dll
  - ls ./XUnitTestProject1/bin/Release/
  - dotnet restore ./XUnitTestProject1
  - ls ./XUnitTestProject1/bin/Release/
  - dotnet test ./XUnitTestProject1 --configuration Release --framework netcoreapp1.0
  - dotnet test ./XUnitTestProject1 --configuration Release --framework netcoreapp2.0
  - dotnet test ./XUnitTestProject1 --framework netcoreapp2.0
  - echo --------------
    #####
  - xbuild /p:Configuration=Release SimpleApp.sln
  - ls ./UnitTestProject1/bin/Release/
  - dotnet restore ./UnitTestProject1
  - dotnet test ./UnitTestProject1 --configuration Release --framework netcoreapp2.0
