language: csharp
solution: SimpleApp.sln
install:
  - nuget restore SimpleApp.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
  - nuget xunit.runner.console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SimpleApp.sln
  - ls ./testrunner/
  - ls ./testrunner/xunit.runners.2.0.0/
  - ls ./testrunner/xunit.runners.2.3.1/
  - ls ./UnitTestProject1/bin/Release/
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./UnitTestProject1/bin/Release/UnitTestProject1.dll
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/netcoreapp1.0/xunit.console.dll ./UnitTestProject1/bin/Release/UnitTestProject1.dll
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/netcoreapp2.0/xunit.console.dll ./UnitTestProject1/bin/Release/UnitTestProject1.dll
