language: csharp
solution: SimpleApp.sln
msbuild: 15.5.180
mono: 5.0.0
dotnet: 2.0.0

install:
  - nuget restore SimpleApp.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
  - dotnet restore

script:
  - echo "--------"
#  - xbuild /p:Configuration=Release SimpleApp.sln
#  - dotnet test ./StandartClassLibrary --configuration Release --framework netcoreapp2.0
#  - dotnet test ./StandartClassLibrary --configuration Release --framework net452
#  - dotnet build --configuration Release --framework netcoreapp2.0
  
  - msbuild /p:Configuration=Release /p:targetframework=net40 SimpleApp.sln   # output: Release/net40
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./SomeTests/bin/Release/net40/SomeTests.dll
#  - ls SimpleApp/bin/Release
#  - ls SimpleApp/bin/Release/net40
  - dotnet build --framework netstandard1.2
  - dotnet build
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./SomeTests/bin/Release/netstandard1.2/SomeTests.dll
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/netcoreapp2.0/xunit.console.exe ./SomeTests/bin/Release/netstandard2.0/SomeTests.dll
