language: csharp
solution: SimpleApp.sln
mono: 5.0.0
dotnet: 2.0.0

install:
  - nuget restore SimpleApp.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
  - dotnet restore

script:
  - echo "--------"
#  - xbuild /p:Configuration=Release SimpleApp.sln
#  - dotnet test ./StandartClassLibrary --configuration Release --framework netcoreapp2.0
#  - dotnet test ./StandartClassLibrary --configuration Release --framework net452
#  - dotnet build --configuration Release --framework netcoreapp2.0
  - dotnet restore SimpleApp
  - ls StandartClassLibrary
  - dotnet restore StandartClassLibrary
  - ls StandartClassLibrary
  - msbuild /p:Configuration=Release
  - ls StandartClassLibrary/bin/Release
  - ls StandartClassLibrary/bin/Release/net452
#  - msbuild /p:Configuration=Release SimpleApp.sln   # output: Release/net452
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./StandartClassLibrary/bin/Release/net452/StandartClassLibrary.dll
