language: csharp
solution: SimpleApp.sln
install:
  - nuget restore SimpleApp.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SimpleApp.sln
  - ls ./testrunner/xunit.runners.2.0.0/tools/
  - ls ./UnitTestProject1/bin/Release/
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./UnitTestProject1/bin/Release/UnitTestProject1.dll
